### ISSUE TITLE
Veloren does not start if Airshipper is put out of focus while starting the game

### ISSUE THREAD

**Issue by DaforLynx** [Songtronix/Airshipper#93] opened 2020-09-15 21:32 UTC
Title
If I alt tab or use another window out of Airshipper right after pressing "Play" the game will not start, and Airshipper will disappear from Task Manager. This is a hard bug to reproduce if the game starts quickly; it's most noticeable after updating, when it takes slightly longer for the process to start.

**Comment by Songtronix** [comment] 2020-11-14 07:57
As I want to push 0.4.1 further along as it already fixes important things and it probably will take some time to find out the cause of this issue I'll target to fix it with 0.4.2.

**Comment by Songtronix** [comment] 2020-12-16 19:35
Probably fixed with 0.4.2. Reopen incase it happens again.

**Closed by Songtronix** 2020-12-16 19:35 UTC
Labels: help wanted, pri: important, status: waiting for merge, type: bug
